import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "../lib/util/ReactQueryProvider";
import NavBar from "@/components/common/navbar/NavBar";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ReactQueryProvider>
          <Header />
          <main className="h-[634px]">{children}</main>
          <NavBar />
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
